"""reverse_sync_offer_id

Revision ID: 2adbd3c7e4f6
Revises: d800268f3c5d
Create Date: 2024-09-18 11:57:08.057592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2adbd3c7e4f6'
down_revision: Union[str, None] = 'd800268f3c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('reverse_sync_offer_id', sa.Integer(), nullable=True, server_default=sa.null()))
    op.create_foreign_key(None, 'catalog_items', 'offers', ['reverse_sync_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_items', type_='foreignkey')
    op.drop_column('catalog_items', 'reverse_sync_offer_id')
    # ### end Alembic commands ###
