"""update_orders

Revision ID: 6244d35c024e
Revises: 21405234945f
Create Date: 2024-09-12 18:24:49.746883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6244d35c024e'
down_revision: Union[str, None] = '21405234945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('internal_order_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('orders_warehouse_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_warehouse_id_fkey', 'orders', 'warehouses', ['warehouse_id'], ['id'], ondelete='CASCADE')
    op.drop_column('orders', 'internal_order_id')
    # ### end Alembic commands ###
