"""track sizes

Revision ID: 7b8443c244a7
Revises: f550d9f0cb03
Create Date: 2024-09-14 14:17:41.011877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8443c244a7'
down_revision: Union[str, None] = 'f550d9f0cb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('self_weight_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('self_length_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('self_width_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('self_height_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'self_height_changed')
    op.drop_column('offers', 'self_width_changed')
    op.drop_column('offers', 'self_length_changed')
    op.drop_column('offers', 'self_weight_changed')
    # ### end Alembic commands ###
