"""add dollar_cost_price_updated_at

Revision ID: af3dafb05016
Revises: 0e096f590920
Create Date: 2024-08-25 20:44:20.282034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3dafb05016'
down_revision: Union[str, None] = '0e096f590920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('dollar_cost_price_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'dollar_cost_price_updated_at')
    # ### end Alembic commands ###
