"""new_fields

Revision ID: d800268f3c5d
Revises: ea08934f3fa7
Create Date: 2024-09-17 23:23:38.735026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd800268f3c5d'
down_revision: Union[str, None] = 'ea08934f3fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('use_promotion_price_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('wholesale_dollar_cost_price_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('supplier_available_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'supplier_available_changed')
    op.drop_column('catalog_items', 'wholesale_dollar_cost_price_changed')
    op.drop_column('catalog_items', 'use_promotion_price_changed')
    # ### end Alembic commands ###
