"""reverse_synchronization

Revision ID: ea08934f3fa7
Revises: db878a5d9872
Create Date: 2024-09-17 01:05:18.532216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea08934f3fa7'
down_revision: Union[str, None] = 'db878a5d9872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('reverse_synchronization', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'reverse_synchronization')
    # ### end Alembic commands ###
