services:
  backend:
    restart: unless-stopped
    env_file: backend/.env.local
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ./logs:/backend/logs
    expose:
      - 8000
    ports:
      - "8000:8000"

  frontend:
    restart: unless-stopped
    env_file: front/.env.local
    build:
      context: front
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx/local:/etc/nginx/conf.d
      - ./certs:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443

  database:
    restart: unless-stopped
    image: postgres:17.0
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data-local: