services:
  wb-mock:
    build:
      context: mocks/wb-mock
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8001

  ozon-mock:
    build:
      context: mocks/ozon-mock
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8002

  backend:
    restart: unless-stopped
    env_file: backend/.env.prod
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - database
      - wb-mock
      - ozon-mock
    environment:
      WB_API_BASE_URL: "http://localhost:8001"
      OZON_API_BASE_URL: "http://localhost:8002"
    volumes:
      - ./logs:/backend/logs
    expose:
      - 8000

  node_exporter:
    image: prom/node-exporter:v1.9.1
    container_name: woym_market_node_exporter
    restart: unless-stopped
    pid: host
    ports:
      - "9100:9100"  # Prometheus node metrics scrape
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

  frontend:
    restart: unless-stopped
    env_file: front/.env.prod
    build:
      context: front
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - 3000

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./nginx/prod:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    ports:
      - 80:80
      - 443:443

  database:
    restart: unless-stopped
    image: postgres:17.0
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data-prod: