"""use_smart_delivery

Revision ID: 0041a8ca2dad
Revises: 6767593932be
Create Date: 2024-10-13 17:26:09.839992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0041a8ca2dad'
down_revision: Union[str, None] = '6767593932be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('offers_stocks', sa.Column('use_smart_delivery', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers_stocks', 'use_smart_delivery')

    # ### end Alembic commands ###
