"""consider_logistic_cost

Revision ID: 0886a6685946
Revises: be8808312224
Create Date: 2024-09-24 14:40:16.223910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0886a6685946'
down_revision: Union[str, None] = 'be8808312224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('consider_logistic_cost', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'consider_logistic_cost')
    # ### end Alembic commands ###
