"""rename note to catalog_note and add description

Revision ID: 0e096f590920
Revises: bf8560fc9a02
Create Date: 2024-08-23 01:55:14.303402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e096f590920'
down_revision: Union[str, None] = 'bf8560fc9a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('catalog_note', sa.String(), server_default=sa.text("'Новый товар'"), nullable=True))
    op.drop_column('catalog_items', 'note')
    op.add_column('offers', sa.Column('catalog_note', sa.String(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'catalog_note')
    op.add_column('catalog_items', sa.Column('note', sa.VARCHAR(), server_default=sa.text("'Новый товар'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('catalog_items', 'catalog_note')
    # ### end Alembic commands ###
