"""smart delivery

Revision ID: 21405234945f
Revises: f3c5c27d7769
Create Date: 2024-09-11 12:51:13.003648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21405234945f'
down_revision: Union[str, None] = 'f3c5c27d7769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('a_variable_for_smart_delivery', sa.Float(), server_default=sa.text("0"), nullable=False))
    op.add_column('markets', sa.Column('b_variable_for_smart_delivery', sa.Float(), server_default=sa.text("0"), nullable=False))
    op.add_column('markets', sa.Column('c_variable_for_smart_delivery', sa.Float(), server_default=sa.text("0"), nullable=False))
    op.add_column('markets', sa.Column('d_variable_for_smart_delivery', sa.Float(), server_default=sa.text("0"), nullable=False))
    op.add_column('markets', sa.Column('e_variable_for_smart_delivery', sa.Float(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'e_variable_for_smart_delivery')
    op.drop_column('markets', 'd_variable_for_smart_delivery')
    op.drop_column('markets', 'c_variable_for_smart_delivery')
    op.drop_column('markets', 'b_variable_for_smart_delivery')
    op.drop_column('markets', 'a_variable_for_smart_delivery')
    # ### end Alembic commands ###
