"""empty message

Revision ID: 49dd96946954
Revises: 
Create Date: 2024-08-17 23:26:24.291056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dd96946954'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('catalog_items', 'annotation', server_default=None)
    op.add_column('offers', sa.Column('description', sa.String(), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'description')
    op.add_column('catalog_items', sa.Column('annotation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('catalog_items', 'description')
    # ### end Alembic commands ###
