"""remove volumes

Revision ID: 5c0b3d95d71f
Revises: 0b466babc25c
Create Date: 2024-09-22 16:36:57.467771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0b3d95d71f'
down_revision: Union[str, None] = '0b466babc25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'volume')
    op.drop_column('offers', 'volume')
    op.drop_column('offers', 'volume_difference')
    op.drop_column('offers', 'yandex_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('yandex_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('volume_difference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
