"""new tracker

Revision ID: 6767593932be
Revises: 949d3ddb0a3f
Create Date: 2024-09-28 03:05:47.504073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6767593932be'
down_revision: Union[str, None] = '949d3ddb0a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('use_promotion_price_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'use_promotion_price_changed')
    # ### end Alembic commands ###
