"""new tracker

Revision ID: 949d3ddb0a3f
Revises: 0886a6685946
Create Date: 2024-09-28 03:02:51.154738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949d3ddb0a3f'
down_revision: Union[str, None] = '0886a6685946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('dollar_cost_price_updated_at_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('dollar_cost_price_updated_at_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('supplier_available_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('wholesale_dollar_cost_price_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'wholesale_dollar_cost_price_changed')
    op.drop_column('offers', 'supplier_available_changed')
    op.drop_column('offers', 'dollar_cost_price_updated_at_changed')
    op.drop_column('catalog_items', 'dollar_cost_price_updated_at_changed')
    # ### end Alembic commands ###
