"""default offer values

Revision ID: be8808312224
Revises: 5c0b3d95d71f
Create Date: 2024-09-22 21:10:59.153702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8808312224'
down_revision: Union[str, None] = '5c0b3d95d71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('default_auto_min_price', sa.Float(), nullable=False, server_default="100"))
    op.add_column('markets', sa.Column('default_auto_price_control', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('markets', sa.Column('default_total_price_coeff', sa.Float(), nullable=False, server_default="2.4"))
    op.add_column('markets', sa.Column('default_total_price_min_additional', sa.Float(), nullable=False, server_default="200"))
    op.add_column('markets', sa.Column('default_auto_participation_in_promotions', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('markets', sa.Column('default_pricing_scheme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'default_pricing_scheme')
    op.drop_column('markets', 'default_auto_participation_in_promotions')
    op.drop_column('markets', 'default_total_price_min_additional')
    op.drop_column('markets', 'default_total_price_coeff')
    op.drop_column('markets', 'default_auto_price_control')
    op.drop_column('markets', 'default_auto_min_price')
    # ### end Alembic commands ###
