"""empty message

Revision ID: bf8560fc9a02
Revises: 49dd96946954
Create Date: 2024-08-17 23:30:20.131768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8560fc9a02'
down_revision: Union[str, None] = '49dd96946954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('name_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('description_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('barcodes_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'barcodes_changed')
    op.drop_column('offers', 'description_changed')
    op.drop_column('offers', 'name_changed')
    # ### end Alembic commands ###
