"""track catalog changes

Revision ID: db878a5d9872
Revises: 7b8443c244a7
Create Date: 2024-09-16 14:42:22.047686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db878a5d9872'
down_revision: Union[str, None] = '7b8443c244a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('self_weight_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('self_length_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('self_width_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('self_height_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('description_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('name_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('catalog_items', sa.Column('barcodes_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'barcodes_changed')
    op.drop_column('catalog_items', 'name_changed')
    op.drop_column('catalog_items', 'description_changed')
    op.drop_column('catalog_items', 'self_height_changed')
    op.drop_column('catalog_items', 'self_width_changed')
    op.drop_column('catalog_items', 'self_length_changed')
    op.drop_column('catalog_items', 'self_weight_changed')
    # ### end Alembic commands ###
