"""catalog

Revision ID: e692b4aed716
Revises: f9067dd3e84f
Create Date: 2024-09-08 02:27:54.667950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e692b4aed716'
down_revision: Union[str, None] = 'f9067dd3e84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('catalog_items', sa.Column('catalog_note', sa.String(), server_default=sa.text("'Новый товар'"), nullable=True))
    op.add_column('catalog_items', sa.Column('dollar_cost_price_updated_at', sa.DateTime(), nullable=True))
    op.add_column('catalog_items', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('catalog_items', 'note')
    op.drop_column('catalog_items', 'self_volume')
    op.drop_column('catalog_items', 'annotation')
    op.add_column('offers', sa.Column('name_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('description', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('description_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('offers', sa.Column('catalog_note', sa.String(), server_default=sa.text("''"), nullable=False))
    op.add_column('offers', sa.Column('barcodes_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('offers', 'vendor_code',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'vendor_code',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('offers', 'barcodes_changed')
    op.drop_column('offers', 'catalog_note')
    op.drop_column('offers', 'description_changed')
    op.drop_column('offers', 'description')
    op.drop_column('offers', 'name_changed')
    op.add_column('catalog_items', sa.Column('annotation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('self_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('catalog_items', sa.Column('note', sa.VARCHAR(), server_default=sa.text("'Новый товар'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('catalog_items', 'description')
    op.drop_column('catalog_items', 'dollar_cost_price_updated_at')
    op.drop_column('catalog_items', 'catalog_note')
    op.drop_column('catalog_items', 'volume')
    # ### end Alembic commands ###
