"""order with offer relationship

Revision ID: f3c5c27d7769
Revises: f8378c85506c
Create Date: 2024-09-10 00:38:42.002439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c5c27d7769'
down_revision: Union[str, None] = 'f8378c85506c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('offer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'offers', ['offer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'offer_id')
    # ### end Alembic commands ###
