"""photo_changed

Revision ID: f9067dd3e84f
Revises: a7ca8a47b72c
Create Date: 2024-08-29 05:03:59.232030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9067dd3e84f'
down_revision: Union[str, None] = 'a7ca8a47b72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('photo_changed', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'photo_changed')
    # ### end Alembic commands ###
